### ISSUE TITLE
xmldom 1.1.20 breaks jsonix

### ISSUE THREAD

**Issue by azatoth** [highsource/jsonix#134]
After some debugging I suspect that the upgrade of xmldom to 1.1.20 breaks jsonix. A downgrade to 1.1.19 solves the issue

```
TypeError: node.serializeToString is not a function
    at XMLSerializer.serializeToString (/var/www/releases/20160111083622/node_modules/jsonix/node_modules/xmldom/dom.js:906:7)
    at Object.Jsonix.DOM.serialize (/var/www/releases/20160111083622/node_modules/jsonix/jsonix.js:118:50)
    at Object.Jsonix.Binding.Marshaller.Jsonix.Class.marshalString (/var/www/releases/20160111083622/node_modules/jsonix/jsonix.js:2031:25)
    at build (/var/www/releases/20160111083622/src/server/Skatteverket.js:52:23)
    at toString (/var/www/releases/20160111083622/src/server/Skatteverket.js:180:55)
    at /var/www/releases/20160111083622/src/server/company/CompanyRoutes.js:1340:23
From previous event:
    at exports.generateKU28 (/var/www/releases/20160111083622/src/server/company/CompanyRoutes.js:1356:6)
    at callbacks (/var/www/releases/20160111083622/node_modules/express/lib/router/index.js:164:37)
    at param (/var/www/releases/20160111083622/node_modules/express/lib/router/index.js:138:11)
    at paramCallback (/var/www/releases/20160111083622/node_modules/express/lib/router/index.js:150:30)
    at /var/www/releases/20160111083622/src/server/company/CompanyRoutes.js:93:9
```

**Comment by highsource** [comment]
Moved to `xmldom` `>=0.1.21`.
