### ISSUE TITLE
JSDOM breaks jsonix

### ISSUE THREAD

**Issue by noyg** [highsource/jsonix#159]
```
C:\projects\myproj\node_modules\jsonix\jsonix.js:140
			var request = new XMLHttpRequest();
			                  ^

ReferenceError: XMLHttpRequest is not defined
    at Object.Jsonix.DOM.parse (C:\projects\myproj\node_modules\jsonix\jsonix.js:140:22)
    at Object.Jsonix.Binding.Unmarshaller.Jsonix.Class.unmarshalString (C:\projects\myproj\node_modules\jsonix\jsonix.js:2059:24)
    at Request._callback (C:/projects/myprojhelpers/WalmartAPI.js:94:41)
    at Request.self.callback (C:\projects\myproj\node_modules\request\request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\projects\myproj\node_modules\request\request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\projects\myproj\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```

**Comment by highsource** [comment]
Do you know which `jsdom` version it is?

**Comment by highsource** [comment]
Wait a minute... Jsonix does not use JSDOM, it uses `xmldom`.

You'll get an error in this line in case `xmldom` is not defined. I'm curios how this can happen, in the node.js environment `xmldom` will me "required" via `amdefine`.

Please send me a PR with a reproducing project under https://github.com/highsource/jsonix-support/tree/master/w/walmart-api, as contribution under the same license (https://github.com/highsource/jsonix/blob/master/LICENSE).

**Comment by highsource** [comment]
No reproduction - closing.
