### ISSUE TITLE
[question] How to understand Jsonix error?

### ISSUE THREAD

**Issue by gitowiec** [highsource/jsonix#194]
I have successfully generated mappings from this [XSD](https://www.mf.gov.pl/documents/764034/5134536/Schemat_JPK_FA%281%29_v1-0.xsd) and am able to generate my XML using JSON as input data. But when I was coding I had this error:
```
Error: Argument [23] must be a string.
    at Object.ensureString (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:750:10)
    at Class.print (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:4186:22)
    at Class.reprint (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:4078:16)
    at Class.marshal (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:4093:32)
    at Class.marshalElement (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:1877:14)
    at Class.marshal (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:3033:9)
    at Class.marshal (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:2353:21)
    at Class.marshalElement (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:1877:14)
    at Class.marshal (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:3040:10)
    at Class.marshal (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:2353:21)
    at Class.marshalElement (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:1877:14)
    at Class.marshalDocument (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:2040:8)
    at Class.marshalString (/home/marek/workspace/web-server/node_modules/jsonix/jsonix.js:2030:18)
    at JPKXMLService.marshalObjectIntoString (/home/marek/workspace/web-server/src/adapters/services/JPKXMLService.ts:81:34)
    at JPKXMLService.getJPKFAXML (/home/marek/workspace/web-server/src/adapters/services/JPKXMLService.ts:101:19)
    at GetJPKFAUseCase.<anonymous> (/home/marek/workspace/web-server/src/core/usecase/invoices/getJPKFA/GetJPKFAUseCase.ts:47:39)
```
The problem was with one data, that should be a string.
The real problem with this error message is - how to understand this? There is missing information for developer which part of data is wrong (where is argument[23]?). I found it by doing "Divide and rule" and cutting off data from the Marshaller input. What was a little cumbersome.

**Comment by highsource** [comment]
You probably have `23` as a number somewhere in your data, not as a string which is expected.

You are right, information on location of the problem is not available but it would be definitely helpful. Please file a feature request issue.

**Comment by gitowiec** [comment]
Exactly `23` was a sinner. I filed feature-request https://github.com/highsource/jsonix/issues/195
