### ISSUE TITLE
error with any element and xsi:type

### ISSUE THREAD

**Issue by amarant** [highsource/jsonix#96]
Hi,
here is a crash I've got when unmarshaling an xml using xsi:type in an any element.
The error is :
````
Error: Element [INCLUDED] is not known in this context.
    at Object.Jsonix.Binding.Marshalls.Element.Jsonix.Class.marshalElement (\samples\jsonix\nodejs\scripts\jsonix.js:1869:10)
    at Object.Jsonix.Model.AnyElementPropertyInfo.Jsonix.Class.marshalItem (\samples\jsonix\nodejs\scripts\jsonix.js:3652:10)
    at Object.Jsonix.Model.AnyElementPropertyInfo.Jsonix.Class.marshal (\samples\jsonix\nodejs\scripts\jsonix.js:3638:10)
    at Object.Jsonix.Model.ClassInfo.Jsonix.Class.marshal (\samples\jsonix\nodejs\scripts\jsonix.js:2336:21)
    at Object.Jsonix.Binding.Marshalls.Element.Jsonix.Class.marshalElement (\samples\jsonix\nodejs\scripts\jsonix.js:1865:14)
    at Object.Jsonix.Model.AbstractElementsPropertyInfo.Jsonix.Class.marshal (\samples\jsonix\nodejs\scripts\jsonix.js:2989:9)
    at Object.Jsonix.Model.ClassInfo.Jsonix.Class.marshal (\samples\jsonix\nodejs\scripts\jsonix.js:2336:21)
    at Object.Jsonix.Binding.Marshalls.Element.Jsonix.Class.marshalElement (\samples\jsonix\nodejs\scripts\jsonix.js:1865:14)
    at Object.Jsonix.Binding.Marshaller.Jsonix.Class.marshalDocument (\samples\jsonix\nodejs\scripts\jsonix.js:2028:8)
    at \samples\jsonix\nodejs\scripts\tests\roundtrip.js:13:35
````
The repro xsd file : 
`test_any.xsd`
````xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xs:schema targetNamespace="test:any" xmlns:testany="test:any" xml:lang="fr" elementFormDefault="unqualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="MixedAnyType" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:any namespace="##any" processContents="lax"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="INCLUDED">
    <xs:attribute name="majorVersion" type="xs:nonNegativeInteger" use="required">
    </xs:attribute>
  </xs:complexType>
  <xs:element name="TESTANY">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="en"  type="testany:MixedAnyType">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
````
`test_any.xml`
````xml
<?xml version="1.0" encoding="UTF-8"?>
<testany:TESTANY xmlns:testany="test:any" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="test:any test_any.xsd">
    <en>
        <INCLUDED xsi:type="testany:INCLUDED" majorVersion="1"/>
    </en>
</testany:TESTANY>
````

and the mapping file :
````javascript
var test_any_Module_Factory = function () {
  var test_any = {
    name: 'test_any',
    typeInfos: [{
        localName: 'MixedAnyType',
        typeName: {
          namespaceURI: 'test:any',
          localPart: 'MixedAnyType'
        },
        propertyInfos: [{
            name: 'content',
            collection: true,
            type: 'anyElement'
          }]
      }, {
        localName: 'INCLUDED',
        typeName: {
          namespaceURI: 'test:any',
          localPart: 'INCLUDED'
        },
        propertyInfos: [{
            name: 'majorVersion',
            typeInfo: 'Integer',
            attributeName: {
              localPart: 'majorVersion'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'TESTANY',
        typeName: null,
        propertyInfos: [{
            name: 'en',
            elementName: {
              localPart: 'en'
            },
            typeInfo: '.MixedAnyType'
          }]
      }],
    elementInfos: [{
        elementName: {
          localPart: 'TESTANY',
          namespaceURI: 'test:any'
        },
        typeInfo: '.TESTANY'
      }]
  };
  return {
    test_any: test_any
  };
};
if (typeof define === 'function' && define.amd) {
  define([], test_any_Module_Factory);
}
else {
  var test_any_Module = test_any_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.test_any = test_any_Module.test_any;
  }
  else {
    var test_any = test_any_Module.test_any;
  }
}
````
I think the error is in [Unmarshalls.js in function AsElementRef](https://github.com/highsource/jsonix/blob/c974573a9f79f70bface3f07259640c09b6a7e34/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/Binding/Unmarshalls.js#L80) when we use the typedNamedValue.name object that has no namespace, when we could use the typedNamedValue.typeInfo object. It is called from [here](https://github.com/highsource/jsonix/blob/c974573a9f79f70bface3f07259640c09b6a7e34/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/Binding/Unmarshalls.js#L42)

Thanks.

**Comment by amarant** [comment]
So I create a pull request with the repro case like the other ones.

**Comment by highsource** [comment]
Thank you, this looks like a bug. This should work.

**Comment by highsource** [comment]
The problem was actually not in unmarshalling but in marshalling.

**Comment by highsource** [comment]
Should be fixed now.

**Comment by yashutanna** [comment]
any idea when this will be released? or any workarounds

I'm installing using bower, and have the exact same problem

**Comment by highsource** [comment]
Please test the current version:

https://github.com/highsource/jsonix/tree/master/dist

http://stackoverflow.com/questions/16949173/how-to-install-latest-untagged-state-of-a-repo-using-bower

I can release over the weekend.

**Comment by silentFred** [comment]
@yashutanna lol. Yeah just dump the dist in utils and see how far we get =P

**Comment by amarant** [comment]
Thanks it fixes my last round trip error on my tests.
